on:
  push:
    branches:
      - '*'
  pull_request_target:
    types:
      - opened
    branches: [main]
name: Unit Test
jobs:
  test:
    runs-on: ubuntu-latest
    name: Unit Tests
    steps:
      - name: Clone the repository
        uses: actions/checkout@v3
      - name: Test
        run: |
          npm install
          npm run test
